# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: rlucio01.WhisperApp
PackageVersion: 0.4.18
MinimumOSVersion: 10.0.17763.0
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/rlucio01/whisper-app/releases/download/v0.4.18/whisper_app_0.4.18_x64-setup.exe
  InstallerSha256: 6ADA4F287533C618C73EA820AEF38F41357CDF91F7C1896453DEE24F5024F840
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.9.0
